apiVersion: v1
kind: Service
metadata:
  name: deepseek-service
  namespace: default
spec:
  selector:
    app: deepseek
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort